// Code generated by go generate ./...; DO NOT EDIT.
package mcpserver

import (
	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/aarondpn/redmine-cli/v2/internal/api"
	"github.com/aarondpn/redmine-cli/v2/internal/models"
	"github.com/aarondpn/redmine-cli/v2/internal/ops"
)

func registerGeneratedTools(s *mcp.Server, client *api.Client, opts Options) {
	registerToolSpec(s, client, opts, toolSpec[ops.GroupUserInput, ops.MessageResult]{
		Name:        "add_group_user",
		Description: "Add a user to a Redmine group. Requires --enable-writes.",
		Category:    "groups",
		Writes:      true,
		Call:        ops.AddGroupUser,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.CreateGroupInput, *models.Group]{
		Name:        "create_group",
		Description: "Create a new Redmine group. Requires --enable-writes.",
		Category:    "groups",
		Writes:      true,
		Call:        ops.CreateGroup,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.DeleteGroupInput, ops.MessageResult]{
		Name:        "delete_group",
		Description: "Delete a Redmine group. Destructive. Requires --enable-writes.",
		Category:    "groups",
		Writes:      true,
		Call:        ops.DeleteGroup,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.GetGroupInput, *models.Group]{
		Name:        "get_group",
		Description: "Fetch a single Redmine group by ID.",
		Category:    "groups",
		Call:        ops.GetGroup,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.ListGroupsInput, ops.GroupsListResult]{
		Name:        "list_groups",
		Description: "List Redmine groups.",
		Category:    "groups",
		Call:        ops.ListGroups,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.GroupUserInput, ops.MessageResult]{
		Name:        "remove_group_user",
		Description: "Remove a user from a Redmine group. Requires --enable-writes.",
		Category:    "groups",
		Writes:      true,
		Call:        ops.RemoveGroupUser,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.UpdateGroupInput, ops.MessageResult]{
		Name:        "update_group",
		Description: "Update an existing Redmine group. Requires --enable-writes.",
		Category:    "groups",
		Writes:      true,
		Call:        ops.UpdateGroup,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.AddIssueCommentInput, ops.MessageResult]{
		Name:        "add_issue_comment",
		Description: "Add a journal comment to an existing issue. Requires --enable-writes.",
		Category:    "issues",
		Writes:      true,
		Call:        ops.AddIssueComment,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.CloseIssueInput, ops.MessageResult]{
		Name:        "close_issue",
		Description: "Close an issue by setting its status to the first closed status. Requires --enable-writes.",
		Category:    "issues",
		Writes:      true,
		Call:        ops.CloseIssue,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.CreateIssueInput, *models.Issue]{
		Name:        "create_issue",
		Description: "Create a new Redmine issue. Requires --enable-writes.",
		Category:    "issues",
		Writes:      true,
		Call:        ops.CreateIssue,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.DeleteIssueInput, ops.MessageResult]{
		Name:        "delete_issue",
		Description: "Delete a Redmine issue. Destructive. Requires --enable-writes.",
		Category:    "issues",
		Writes:      true,
		Call:        ops.DeleteIssue,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.GetIssueInput, *models.Issue]{
		Name:        "get_issue",
		Description: "Fetch a single Redmine issue by ID.",
		Category:    "issues",
		Call:        ops.GetIssue,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.ListIssuesInput, ops.IssuesListResult]{
		Name:        "list_issues",
		Description: "List Redmine issues matching the given filters.",
		Category:    "issues",
		Call:        ops.ListIssues,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.ReopenIssueInput, ops.MessageResult]{
		Name:        "reopen_issue",
		Description: "Reopen a closed issue by setting its status to the first open status. Requires --enable-writes.",
		Category:    "issues",
		Writes:      true,
		Call:        ops.ReopenIssue,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.UpdateIssueInput, ops.MessageResult]{
		Name:        "update_issue",
		Description: "Update fields on an existing Redmine issue. Requires --enable-writes.",
		Category:    "issues",
		Writes:      true,
		Call:        ops.UpdateIssue,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.CreateMembershipInput, *models.Membership]{
		Name:        "create_membership",
		Description: "Add a user to a project with the given roles. Requires --enable-writes.",
		Category:    "memberships",
		Writes:      true,
		Call:        ops.CreateMembership,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.DeleteMembershipInput, ops.MessageResult]{
		Name:        "delete_membership",
		Description: "Remove a project membership. Destructive. Requires --enable-writes.",
		Category:    "memberships",
		Writes:      true,
		Call:        ops.DeleteMembership,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.GetMembershipInput, *models.Membership]{
		Name:        "get_membership",
		Description: "Fetch a single project membership by ID.",
		Category:    "memberships",
		Call:        ops.GetMembership,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.ListMembershipsInput, ops.MembershipsListResult]{
		Name:        "list_memberships",
		Description: "List memberships for a project.",
		Category:    "memberships",
		Call:        ops.ListMemberships,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.UpdateMembershipInput, ops.MessageResult]{
		Name:        "update_membership",
		Description: "Replace the roles on a project membership. Requires --enable-writes.",
		Category:    "memberships",
		Writes:      true,
		Call:        ops.UpdateMembership,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.CreateVersionInput, *models.Version]{
		Name:        "create_version",
		Description: "Create a project version (milestone). Requires --enable-writes.",
		Category:    "meta",
		Writes:      true,
		Call:        ops.CreateVersion,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.DeleteVersionInput, ops.MessageResult]{
		Name:        "delete_version",
		Description: "Delete a version (milestone). Destructive. Requires --enable-writes.",
		Category:    "meta",
		Writes:      true,
		Call:        ops.DeleteVersion,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.GetCustomFieldInput, *models.CustomField]{
		Name:        "get_custom_field",
		Description: "Fetch a single custom field definition by ID. Admin-only endpoint.",
		Category:    "meta",
		Call:        ops.GetCustomField,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.GetRoleInput, *models.Role]{
		Name:        "get_role",
		Description: "Fetch a single Redmine role by ID, including permissions when available.",
		Category:    "meta",
		Call:        ops.GetRole,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.GetTrackerInput, *models.Tracker]{
		Name:        "get_tracker",
		Description: "Fetch a single tracker by ID, including default status and enabled standard fields when available.",
		Category:    "meta",
		Call:        ops.GetTracker,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.GetVersionInput, *models.Version]{
		Name:        "get_version",
		Description: "Fetch a single version (milestone) by ID.",
		Category:    "meta",
		Call:        ops.GetVersion,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.ListCategoriesInput, ops.CategoriesListResult]{
		Name:        "list_categories",
		Description: "List issue categories for a project.",
		Category:    "meta",
		Call:        ops.ListCategories,
	})
	registerToolSpec(s, client, opts, toolSpec[struct{}, ops.CustomFieldsListResult]{
		Name:        "list_custom_fields",
		Description: "List custom field definitions configured in this Redmine instance. Admin-only endpoint.",
		Category:    "meta",
		Call:        ops.ListCustomFields,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.ListQueriesInput, ops.QueriesListResult]{
		Name:        "list_queries",
		Description: "List saved queries (custom filters) visible to the authenticated user. Pass the returned id to list_issues as query_id to run the query.",
		Category:    "meta",
		Call:        ops.ListQueries,
	})
	registerToolSpec(s, client, opts, toolSpec[struct{}, ops.RolesListResult]{
		Name:        "list_roles",
		Description: "List all Redmine roles configured in this instance.",
		Category:    "meta",
		Call:        ops.ListRoles,
	})
	registerToolSpec(s, client, opts, toolSpec[struct{}, ops.StatusesListResult]{
		Name:        "list_statuses",
		Description: "List all issue statuses configured in this Redmine instance.",
		Category:    "meta",
		Call:        ops.ListStatuses,
	})
	registerToolSpec(s, client, opts, toolSpec[struct{}, ops.TrackersListResult]{
		Name:        "list_trackers",
		Description: "List all trackers (Bug, Feature, ...) configured in this Redmine instance.",
		Category:    "meta",
		Call:        ops.ListTrackers,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.ListVersionsInput, ops.VersionsListResult]{
		Name:        "list_versions",
		Description: "List versions (milestones) for a project.",
		Category:    "meta",
		Call:        ops.ListVersions,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.UpdateVersionInput, ops.MessageResult]{
		Name:        "update_version",
		Description: "Update an existing version (milestone). Requires --enable-writes.",
		Category:    "meta",
		Writes:      true,
		Call:        ops.UpdateVersion,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.CreateProjectInput, *models.Project]{
		Name:        "create_project",
		Description: "Create a new Redmine project. Requires --enable-writes.",
		Category:    "projects",
		Writes:      true,
		Call:        ops.CreateProject,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.DeleteProjectInput, ops.MessageResult]{
		Name:        "delete_project",
		Description: "Delete a Redmine project. Destructive. Requires --enable-writes.",
		Category:    "projects",
		Writes:      true,
		Call:        ops.DeleteProject,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.GetProjectInput, *models.Project]{
		Name:        "get_project",
		Description: "Fetch a single Redmine project by identifier or ID.",
		Category:    "projects",
		Call:        ops.GetProject,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.ListProjectMembersInput, ops.ProjectMembersListResult]{
		Name:        "list_project_members",
		Description: "List members for a Redmine project.",
		Category:    "projects",
		Call:        ops.ListProjectMembers,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.ListProjectsInput, ops.ProjectsListResult]{
		Name:        "list_projects",
		Description: "List Redmine projects.",
		Category:    "projects",
		Call:        ops.ListProjects,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.UpdateProjectInput, ops.MessageResult]{
		Name:        "update_project",
		Description: "Update an existing Redmine project. Requires --enable-writes.",
		Category:    "projects",
		Writes:      true,
		Call:        ops.UpdateProject,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.SearchInput, ops.SearchResultsListResult]{
		Name:        "search",
		Description: "Search across Redmine issues, wiki pages, news, and more. If no type flag is set, issues and wiki pages are included by default.",
		Category:    "search",
		Call:        ops.Search,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.CreateTimeEntryInput, *models.TimeEntry]{
		Name:        "create_time_entry",
		Description: "Log a new time entry. Requires --enable-writes.",
		Category:    "time",
		Writes:      true,
		Call:        ops.CreateTimeEntry,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.DeleteTimeEntryInput, ops.MessageResult]{
		Name:        "delete_time_entry",
		Description: "Delete a time entry. Destructive. Requires --enable-writes.",
		Category:    "time",
		Writes:      true,
		Call:        ops.DeleteTimeEntry,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.GetTimeEntryInput, *models.TimeEntry]{
		Name:        "get_time_entry",
		Description: "Fetch a single time entry by ID.",
		Category:    "time",
		Call:        ops.GetTimeEntry,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.ListTimeEntriesInput, ops.TimeEntriesListResult]{
		Name:        "list_time_entries",
		Description: "List Redmine time entries matching the given filters.",
		Category:    "time",
		Call:        ops.ListTimeEntries,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.SummaryTimeEntriesInput, ops.TimeSummaryResult]{
		Name:        "summary_time_entries",
		Description: "Summarize time entries grouped by day, project, or activity.",
		Category:    "time",
		Call:        ops.SummaryTimeEntries,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.UpdateTimeEntryInput, ops.MessageResult]{
		Name:        "update_time_entry",
		Description: "Update an existing time entry. Requires --enable-writes.",
		Category:    "time",
		Writes:      true,
		Call:        ops.UpdateTimeEntry,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.CreateUserInput, *models.User]{
		Name:        "create_user",
		Description: "Create a new Redmine user. Requires --enable-writes and admin privileges.",
		Category:    "users",
		Writes:      true,
		Call:        ops.CreateUser,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.DeleteUserInput, ops.MessageResult]{
		Name:        "delete_user",
		Description: "Delete a Redmine user. Destructive. Requires --enable-writes.",
		Category:    "users",
		Writes:      true,
		Call:        ops.DeleteUser,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.GetUserInput, *models.User]{
		Name:        "get_user",
		Description: "Fetch a single Redmine user by numeric ID.",
		Category:    "users",
		Call:        ops.GetUser,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.ListUsersInput, ops.UsersListResult]{
		Name:        "list_users",
		Description: "List Redmine users matching the given filter.",
		Category:    "users",
		Call:        ops.ListUsers,
	})
	registerToolSpec(s, client, opts, toolSpec[struct{}, *models.User]{
		Name:        "me",
		Description: "Return the currently authenticated Redmine user.",
		Category:    "users",
		Call:        ops.GetCurrentUser,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.UpdateUserInput, ops.MessageResult]{
		Name:        "update_user",
		Description: "Update an existing Redmine user. Requires --enable-writes.",
		Category:    "users",
		Writes:      true,
		Call:        ops.UpdateUser,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.CreateWikiPageInput, *models.WikiPage]{
		Name:        "create_wiki_page",
		Description: "Create (or overwrite) a wiki page. Requires --enable-writes.",
		Category:    "wiki",
		Writes:      true,
		Call:        ops.CreateWikiPage,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.DeleteWikiPageInput, ops.MessageResult]{
		Name:        "delete_wiki_page",
		Description: "Delete a wiki page. Destructive. Requires --enable-writes.",
		Category:    "wiki",
		Writes:      true,
		Call:        ops.DeleteWikiPage,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.GetWikiPageInput, *models.WikiPage]{
		Name:        "get_wiki_page",
		Description: "Fetch a single wiki page.",
		Category:    "wiki",
		Call:        ops.GetWikiPage,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.ListWikiPagesInput, ops.WikiPagesListResult]{
		Name:        "list_wiki_pages",
		Description: "List wiki pages for a project.",
		Category:    "wiki",
		Call:        ops.ListWikiPages,
	})
	registerToolSpec(s, client, opts, toolSpec[ops.UpdateWikiPageInput, ops.MessageResult]{
		Name:        "update_wiki_page",
		Description: "Update an existing wiki page. Requires --enable-writes.",
		Category:    "wiki",
		Writes:      true,
		Call:        ops.UpdateWikiPage,
	})
}

// generatedToolDescriptors lists every tool registered by registerGeneratedTools
// so the `mcp list-groups` command can render the catalog without spinning up
// an MCP server.
func generatedToolDescriptors() []ToolDescriptor {
	return []ToolDescriptor{
		{Name: "add_group_user", Description: "Add a user to a Redmine group. Requires --enable-writes.", Group: "groups", Writes: true},
		{Name: "create_group", Description: "Create a new Redmine group. Requires --enable-writes.", Group: "groups", Writes: true},
		{Name: "delete_group", Description: "Delete a Redmine group. Destructive. Requires --enable-writes.", Group: "groups", Writes: true},
		{Name: "get_group", Description: "Fetch a single Redmine group by ID.", Group: "groups", Writes: false},
		{Name: "list_groups", Description: "List Redmine groups.", Group: "groups", Writes: false},
		{Name: "remove_group_user", Description: "Remove a user from a Redmine group. Requires --enable-writes.", Group: "groups", Writes: true},
		{Name: "update_group", Description: "Update an existing Redmine group. Requires --enable-writes.", Group: "groups", Writes: true},
		{Name: "add_issue_comment", Description: "Add a journal comment to an existing issue. Requires --enable-writes.", Group: "issues", Writes: true},
		{Name: "close_issue", Description: "Close an issue by setting its status to the first closed status. Requires --enable-writes.", Group: "issues", Writes: true},
		{Name: "create_issue", Description: "Create a new Redmine issue. Requires --enable-writes.", Group: "issues", Writes: true},
		{Name: "delete_issue", Description: "Delete a Redmine issue. Destructive. Requires --enable-writes.", Group: "issues", Writes: true},
		{Name: "get_issue", Description: "Fetch a single Redmine issue by ID.", Group: "issues", Writes: false},
		{Name: "list_issues", Description: "List Redmine issues matching the given filters.", Group: "issues", Writes: false},
		{Name: "reopen_issue", Description: "Reopen a closed issue by setting its status to the first open status. Requires --enable-writes.", Group: "issues", Writes: true},
		{Name: "update_issue", Description: "Update fields on an existing Redmine issue. Requires --enable-writes.", Group: "issues", Writes: true},
		{Name: "create_membership", Description: "Add a user to a project with the given roles. Requires --enable-writes.", Group: "memberships", Writes: true},
		{Name: "delete_membership", Description: "Remove a project membership. Destructive. Requires --enable-writes.", Group: "memberships", Writes: true},
		{Name: "get_membership", Description: "Fetch a single project membership by ID.", Group: "memberships", Writes: false},
		{Name: "list_memberships", Description: "List memberships for a project.", Group: "memberships", Writes: false},
		{Name: "update_membership", Description: "Replace the roles on a project membership. Requires --enable-writes.", Group: "memberships", Writes: true},
		{Name: "create_version", Description: "Create a project version (milestone). Requires --enable-writes.", Group: "meta", Writes: true},
		{Name: "delete_version", Description: "Delete a version (milestone). Destructive. Requires --enable-writes.", Group: "meta", Writes: true},
		{Name: "get_custom_field", Description: "Fetch a single custom field definition by ID. Admin-only endpoint.", Group: "meta", Writes: false},
		{Name: "get_role", Description: "Fetch a single Redmine role by ID, including permissions when available.", Group: "meta", Writes: false},
		{Name: "get_tracker", Description: "Fetch a single tracker by ID, including default status and enabled standard fields when available.", Group: "meta", Writes: false},
		{Name: "get_version", Description: "Fetch a single version (milestone) by ID.", Group: "meta", Writes: false},
		{Name: "list_categories", Description: "List issue categories for a project.", Group: "meta", Writes: false},
		{Name: "list_custom_fields", Description: "List custom field definitions configured in this Redmine instance. Admin-only endpoint.", Group: "meta", Writes: false},
		{Name: "list_queries", Description: "List saved queries (custom filters) visible to the authenticated user. Pass the returned id to list_issues as query_id to run the query.", Group: "meta", Writes: false},
		{Name: "list_roles", Description: "List all Redmine roles configured in this instance.", Group: "meta", Writes: false},
		{Name: "list_statuses", Description: "List all issue statuses configured in this Redmine instance.", Group: "meta", Writes: false},
		{Name: "list_trackers", Description: "List all trackers (Bug, Feature, ...) configured in this Redmine instance.", Group: "meta", Writes: false},
		{Name: "list_versions", Description: "List versions (milestones) for a project.", Group: "meta", Writes: false},
		{Name: "update_version", Description: "Update an existing version (milestone). Requires --enable-writes.", Group: "meta", Writes: true},
		{Name: "create_project", Description: "Create a new Redmine project. Requires --enable-writes.", Group: "projects", Writes: true},
		{Name: "delete_project", Description: "Delete a Redmine project. Destructive. Requires --enable-writes.", Group: "projects", Writes: true},
		{Name: "get_project", Description: "Fetch a single Redmine project by identifier or ID.", Group: "projects", Writes: false},
		{Name: "list_project_members", Description: "List members for a Redmine project.", Group: "projects", Writes: false},
		{Name: "list_projects", Description: "List Redmine projects.", Group: "projects", Writes: false},
		{Name: "update_project", Description: "Update an existing Redmine project. Requires --enable-writes.", Group: "projects", Writes: true},
		{Name: "search", Description: "Search across Redmine issues, wiki pages, news, and more. If no type flag is set, issues and wiki pages are included by default.", Group: "search", Writes: false},
		{Name: "create_time_entry", Description: "Log a new time entry. Requires --enable-writes.", Group: "time", Writes: true},
		{Name: "delete_time_entry", Description: "Delete a time entry. Destructive. Requires --enable-writes.", Group: "time", Writes: true},
		{Name: "get_time_entry", Description: "Fetch a single time entry by ID.", Group: "time", Writes: false},
		{Name: "list_time_entries", Description: "List Redmine time entries matching the given filters.", Group: "time", Writes: false},
		{Name: "summary_time_entries", Description: "Summarize time entries grouped by day, project, or activity.", Group: "time", Writes: false},
		{Name: "update_time_entry", Description: "Update an existing time entry. Requires --enable-writes.", Group: "time", Writes: true},
		{Name: "create_user", Description: "Create a new Redmine user. Requires --enable-writes and admin privileges.", Group: "users", Writes: true},
		{Name: "delete_user", Description: "Delete a Redmine user. Destructive. Requires --enable-writes.", Group: "users", Writes: true},
		{Name: "get_user", Description: "Fetch a single Redmine user by numeric ID.", Group: "users", Writes: false},
		{Name: "list_users", Description: "List Redmine users matching the given filter.", Group: "users", Writes: false},
		{Name: "me", Description: "Return the currently authenticated Redmine user.", Group: "users", Writes: false},
		{Name: "update_user", Description: "Update an existing Redmine user. Requires --enable-writes.", Group: "users", Writes: true},
		{Name: "create_wiki_page", Description: "Create (or overwrite) a wiki page. Requires --enable-writes.", Group: "wiki", Writes: true},
		{Name: "delete_wiki_page", Description: "Delete a wiki page. Destructive. Requires --enable-writes.", Group: "wiki", Writes: true},
		{Name: "get_wiki_page", Description: "Fetch a single wiki page.", Group: "wiki", Writes: false},
		{Name: "list_wiki_pages", Description: "List wiki pages for a project.", Group: "wiki", Writes: false},
		{Name: "update_wiki_page", Description: "Update an existing wiki page. Requires --enable-writes.", Group: "wiki", Writes: true},
	}
}
